import Footer from "../../components/footer";
import Nav from "../../components/nav";
export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Sin Demora</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <link rel="icon" href="/icon-512x512.png" />
      </Head>
      <main>{children}</main>
    </>
  );
}
